"""
report_generator.py — Automated clinical claims adjudication report generator.

Generates a complete structured report from an AdjudicationResult with:
  - Executive Summary (decision + plain-English narrative)
  - Patient & Claim Metadata
  - Clinical Findings (diagnoses, procedures, symptoms, medications)
  - Medical Code Analysis (ICD-10 + CPT with descriptions)
  - Policy Rule Evaluation (all rules, pass/fail, reasons)
  - Edge Case Analysis (anomalies detected)
  - Clinical Guideline Citations (RAG passages cited)
  - Imaging Analysis (if applicable)
  - Risk Assessment
  - Recommended Actions (numbered, specific, actionable)
  - Pipeline Audit Trail
  - Report Signature & Metadata

Output formats:
  - dict  — structured Python dict (for API / JSON response)
  - json  — formatted JSON string
  - html  — full HTML document (print-ready, PDF-convertible)
  - text  — plain text (for email / logging)
  - markdown — formatted markdown

Usage:
    from agent.reporting.report_generator import ReportGenerator
    gen    = ReportGenerator()
    report = gen.generate(adjudication_result, claim_input)
    html   = report.to_html()
    pdf    = report.to_pdf()   # requires: pip install weasyprint
"""

import json
import logging
import os
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional

from agent.models.enums import ClaimDecision, Severity
from agent.models.schemas import AdjudicationResult, TokenizedClaimInput

logger = logging.getLogger(__name__)

REPORT_VERSION = "1.0.0"


# ─────────────────────────────────────────────
# REPORT DATA STRUCTURE
# ─────────────────────────────────────────────

@dataclass
class ReportSection:
    title:   str
    content: str
    items:   list[dict] = field(default_factory=list)
    severity: Optional[str] = None


@dataclass
class ClinicalReport:
    """
    A fully structured clinical adjudication report.
    Generated by ReportGenerator.generate().
    """
    # Core identity
    report_id:       str
    generated_at:    datetime
    report_version:  str

    # Claim info
    claim_id:        str
    audit_trace_id:  str
    decided_at:      datetime

    # Decision
    decision:        str
    confidence_score:float
    decision_colour: str   # hex colour for rendering

    # Sections
    executive_summary:   ReportSection
    patient_metadata:    ReportSection
    clinical_findings:   ReportSection
    code_analysis:       ReportSection
    rule_evaluation:     ReportSection
    edge_case_analysis:  ReportSection
    guideline_citations: ReportSection
    imaging_analysis:    ReportSection
    risk_assessment:     ReportSection
    recommended_actions: ReportSection
    audit_trail:         ReportSection
    report_signature:    ReportSection

    def to_dict(self) -> dict:
        """Returns full report as structured dict."""
        return {
            "report_id":      self.report_id,
            "generated_at":   self.generated_at.isoformat(),
            "report_version": self.report_version,
            "claim_id":       self.claim_id,
            "audit_trace_id": self.audit_trace_id,
            "decided_at":     self.decided_at.isoformat(),
            "decision":       self.decision,
            "confidence_score": self.confidence_score,
            "sections": {
                "executive_summary":   self._section_dict(self.executive_summary),
                "patient_metadata":    self._section_dict(self.patient_metadata),
                "clinical_findings":   self._section_dict(self.clinical_findings),
                "code_analysis":       self._section_dict(self.code_analysis),
                "rule_evaluation":     self._section_dict(self.rule_evaluation),
                "edge_case_analysis":  self._section_dict(self.edge_case_analysis),
                "guideline_citations": self._section_dict(self.guideline_citations),
                "imaging_analysis":    self._section_dict(self.imaging_analysis),
                "risk_assessment":     self._section_dict(self.risk_assessment),
                "recommended_actions": self._section_dict(self.recommended_actions),
                "audit_trail":         self._section_dict(self.audit_trail),
                "report_signature":    self._section_dict(self.report_signature),
            }
        }

    def to_json(self, indent: int = 2) -> str:
        return json.dumps(self.to_dict(), indent=indent, default=str)

    def to_text(self) -> str:
        """Plain text report — suitable for email or logging."""
        lines = []
        w = 68

        def line(char="─"): lines.append(char * w)
        def header(text):   lines.append(f"  {text}")
        def blank():        lines.append("")

        line("═")
        header("CLAIMIQ — HEALTHCARE CLAIMS ADJUDICATION REPORT")
        line("═")
        header(f"Report ID    : {self.report_id}")
        header(f"Generated    : {self.generated_at.strftime('%Y-%m-%d %H:%M:%S UTC')}")
        header(f"Claim ID     : {self.claim_id}")
        header(f"Audit Trace  : {self.audit_trace_id}")
        header(f"Decided      : {self.decided_at.strftime('%Y-%m-%d %H:%M:%S UTC')}")
        line("═")
        blank()

        sections = [
            self.executive_summary, self.patient_metadata, self.clinical_findings,
            self.code_analysis, self.rule_evaluation, self.edge_case_analysis,
            self.guideline_citations, self.imaging_analysis, self.risk_assessment,
            self.recommended_actions, self.audit_trail, self.report_signature,
        ]

        for section in sections:
            if not section.content and not section.items:
                continue
            lines.append(f"  ── {section.title.upper()} {'─' * max(2, w - len(section.title) - 6)}")
            if section.content:
                for para in section.content.split("\n"):
                    lines.append(f"  {para}")
            if section.items:
                for item in section.items:
                    if isinstance(item, dict):
                        for k, v in item.items():
                            if v:
                                lines.append(f"    {k}: {v}")
                    blank()
            blank()

        line("═")
        lines.append("  END OF REPORT — CLAIMIQ HEALTHCARE CLAIMS ADJUDICATION AGENT")
        line("═")
        return "\n".join(lines)

    def to_markdown(self) -> str:
        """Markdown report — for GitHub, documentation, or rendering."""
        lines = []

        dec_emoji = {"approved": "✅", "rejected": "❌", "needs_review": "⚠️"}.get(self.decision, "📋")
        conf_pct  = f"{self.confidence_score:.0%}"

        lines.append(f"# {dec_emoji} ClaimIQ Adjudication Report")
        lines.append(f"")
        lines.append(f"| Field | Value |")
        lines.append(f"|---|---|")
        lines.append(f"| Report ID | `{self.report_id}` |")
        lines.append(f"| Generated | {self.generated_at.strftime('%Y-%m-%d %H:%M UTC')} |")
        lines.append(f"| Claim ID | `{self.claim_id}` |")
        lines.append(f"| Audit Trace | `{self.audit_trace_id}` |")
        lines.append(f"| **Decision** | **{self.decision.upper().replace('_',' ')}** |")
        lines.append(f"| Confidence | {conf_pct} |")
        lines.append("")

        sections = [
            self.executive_summary, self.clinical_findings, self.code_analysis,
            self.rule_evaluation, self.edge_case_analysis, self.risk_assessment,
            self.recommended_actions, self.guideline_citations,
        ]

        for section in sections:
            if not section.content and not section.items:
                continue
            lines.append(f"## {section.title}")
            if section.content:
                lines.append(section.content)
            if section.items:
                for item in section.items:
                    if isinstance(item, dict):
                        label = item.get("label", "")
                        value = item.get("value", "")
                        status= item.get("status", "")
                        if status == "pass":
                            lines.append(f"- ✅ **{label}**: {value}")
                        elif status == "fail":
                            lines.append(f"- ❌ **{label}**: {value}")
                        elif status == "warn":
                            lines.append(f"- ⚠️ **{label}**: {value}")
                        else:
                            lines.append(f"- **{label}**: {value}" if label else f"- {value}")
            lines.append("")

        return "\n".join(lines)

    def to_html(self) -> str:
        """
        Full HTML report — print-ready, PDF-convertible.
        Includes embedded CSS for professional clinical document styling.
        """
        dec = self.decision
        conf_pct = f"{self.confidence_score:.0%}"

        # Colours per decision
        if dec == "approved":
            dec_colour = "#0a7c52"; dec_bg = "#ecfdf5"; dec_border = "#a7f3d0"
            dec_label  = "APPROVED"; dec_icon = "✓"
        elif dec == "rejected":
            dec_colour = "#c41c3a"; dec_bg = "#fff1f2"; dec_border = "#fecdd3"
            dec_label  = "REJECTED"; dec_icon = "✗"
        else:
            dec_colour = "#92400e"; dec_bg = "#fffbeb"; dec_border = "#fde68a"
            dec_label  = "NEEDS REVIEW"; dec_icon = "!"

        css = f"""
        @import url('https://fonts.googleapis.com/css2?family=DM+Mono:wght@300;400;500&family=Fraunces:ital,opsz,wght@0,9..144,400;0,9..144,600;1,9..144,400&family=DM+Sans:opsz,wght@9..40,300;9..40,400;9..40,500;9..40,600&display=swap');
        * {{ box-sizing: border-box; margin: 0; padding: 0; }}
        body {{ font-family: 'DM Sans', sans-serif; background: #f8f7f3; color: #1a1a18; font-size: 13px; line-height: 1.6; }}
        .page {{ max-width: 900px; margin: 0 auto; padding: 40px 48px; background: #fff; min-height: 100vh; }}
        @media print {{ body {{ background: #fff; }} .page {{ padding: 20px 28px; max-width: 100%; }} .no-print {{ display: none; }} }}

        /* Header */
        .report-header {{ border-bottom: 2px solid #1d4ed8; padding-bottom: 20px; margin-bottom: 28px; }}
        .logo-row {{ display: flex; align-items: center; gap: 12px; margin-bottom: 16px; }}
        .logo-mark {{ width: 36px; height: 36px; border-radius: 8px; background: linear-gradient(135deg, #1d4ed8, #6d28d9); display: flex; align-items: center; justify-content: center; color: #fff; font-family: 'DM Mono', monospace; font-size: 12px; font-weight: 500; }}
        .logo-name {{ font-family: 'Fraunces', serif; font-size: 1.4rem; color: #1a1a18; }}
        .logo-sub {{ font-family: 'DM Mono', monospace; font-size: 0.65rem; color: #9a9888; }}
        .meta-grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 4px 32px; }}
        .meta-row {{ display: flex; gap: 8px; font-size: 0.75rem; }}
        .meta-label {{ color: #9a9888; font-family: 'DM Mono', monospace; width: 100px; flex-shrink: 0; }}
        .meta-value {{ color: #1a1a18; font-family: 'DM Mono', monospace; }}

        /* Decision banner */
        .decision-banner {{ background: {dec_bg}; border: 1.5px solid {dec_border}; border-radius: 12px; padding: 20px 24px; margin-bottom: 28px; display: flex; align-items: flex-start; gap: 16px; }}
        .decision-icon {{ width: 44px; height: 44px; border-radius: 12px; background: {dec_bg}; border: 2px solid {dec_colour}; color: {dec_colour}; display: flex; align-items: center; justify-content: center; font-size: 1.2rem; font-weight: 700; flex-shrink: 0; }}
        .decision-title {{ font-family: 'Fraunces', serif; font-size: 1.6rem; color: {dec_colour}; letter-spacing: -0.02em; line-height: 1; margin-bottom: 4px; }}
        .decision-conf {{ font-family: 'DM Mono', monospace; font-size: 0.72rem; color: {dec_colour}; opacity: 0.8; margin-bottom: 10px; }}
        .decision-narrative {{ font-size: 0.85rem; color: #5a5850; line-height: 1.65; }}

        /* Sections */
        .section {{ margin-bottom: 28px; }}
        .section-title {{ font-family: 'DM Mono', monospace; font-size: 0.6rem; letter-spacing: 0.14em; text-transform: uppercase; color: #9a9888; margin-bottom: 12px; display: flex; align-items: center; gap: 8px; }}
        .section-title::after {{ content: ''; flex: 1; height: 1px; background: #e2e0d8; }}

        /* Code chips */
        .codes-grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 8px; }}
        .code-chip {{ background: #f8f7f3; border: 1px solid #e2e0d8; border-radius: 8px; padding: 10px 12px; }}
        .code-number {{ font-family: 'DM Mono', monospace; font-size: 0.95rem; font-weight: 500; color: #1d4ed8; }}
        .code-number.cpt {{ color: #6d28d9; }}
        .code-desc {{ font-size: 0.75rem; color: #5a5850; margin-top: 3px; line-height: 1.3; }}
        .code-conf {{ font-family: 'DM Mono', monospace; font-size: 0.6rem; color: #9a9888; margin-top: 4px; }}

        /* Rules */
        .rule-row {{ display: flex; align-items: flex-start; gap: 10px; padding: 9px 0; border-bottom: 1px solid #f0efe9; }}
        .rule-row:last-child {{ border: none; }}
        .rule-icon {{ width: 18px; height: 18px; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 0.6rem; font-weight: 700; flex-shrink: 0; margin-top: 1px; }}
        .ri-pass {{ background: #ecfdf5; color: #0a7c52; border: 1px solid #a7f3d0; }}
        .ri-fail {{ background: #fff1f2; color: #c41c3a; border: 1px solid #fecdd3; }}
        .ri-warn {{ background: #fffbeb; color: #92400e; border: 1px solid #fde68a; }}
        .rule-id {{ font-family: 'DM Mono', monospace; font-size: 0.72rem; font-weight: 500; color: #1a1a18; }}
        .rule-reason {{ font-size: 0.73rem; color: #5a5850; line-height: 1.4; margin-top: 2px; }}

        /* Edge cases */
        .edge-card {{ background: #fff1f2; border: 1px solid #fecdd3; border-radius: 8px; padding: 10px 12px; margin-bottom: 8px; }}
        .edge-card.warn {{ background: #fffbeb; border-color: #fde68a; }}
        .edge-type {{ font-family: 'DM Mono', monospace; font-size: 0.68rem; color: #c41c3a; font-weight: 500; }}
        .edge-card.warn .edge-type {{ color: #92400e; }}
        .edge-desc {{ font-size: 0.73rem; color: #5a5850; margin-top: 4px; line-height: 1.4; }}
        .edge-rec {{ font-size: 0.72rem; color: #1a1a18; font-style: italic; margin-top: 6px; }}

        /* Actions */
        .action-list {{ display: flex; flex-direction: column; gap: 6px; }}
        .action-item {{ display: flex; gap: 10px; padding: 10px 12px; border-radius: 8px; border: 1px solid; align-items: flex-start; }}
        .action-item.primary {{ background: #eff6ff; border-color: #bfdbfe; }}
        .action-item.danger  {{ background: #fff1f2; border-color: #fecdd3; }}
        .action-item.warn    {{ background: #fffbeb; border-color: #fde68a; }}
        .action-item.neutral {{ background: #f8f7f3; border-color: #e2e0d8; }}
        .action-num {{ width: 22px; height: 22px; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-family: 'DM Mono', monospace; font-size: 0.62rem; font-weight: 600; flex-shrink: 0; }}
        .action-text {{ font-size: 0.78rem; color: #1a1a18; line-height: 1.5; }}

        /* Chain */
        .chain-step {{ display: flex; gap: 12px; padding: 8px 0; position: relative; }}
        .chain-step::before {{ content: ''; position: absolute; left: 9px; top: 26px; bottom: -8px; width: 1px; background: #e2e0d8; }}
        .chain-step:last-child::before {{ display: none; }}
        .chain-dot {{ width: 20px; height: 20px; border-radius: 50%; background: #eff6ff; border: 2px solid #1d4ed8; flex-shrink: 0; margin-top: 2px; }}
        .chain-stage {{ font-family: 'DM Mono', monospace; font-size: 0.6rem; color: #1d4ed8; text-transform: uppercase; letter-spacing: 0.06em; font-weight: 500; }}
        .chain-outcome {{ font-size: 0.74rem; color: #5a5850; line-height: 1.4; margin-top: 2px; }}

        /* Guideline citations */
        .citation {{ background: #f0efe9; border-left: 3px solid #1d4ed8; border-radius: 0 6px 6px 0; padding: 10px 14px; margin-bottom: 8px; }}
        .citation-source {{ font-family: 'DM Mono', monospace; font-size: 0.62rem; color: #1d4ed8; font-weight: 500; margin-bottom: 4px; }}
        .citation-text {{ font-size: 0.73rem; color: #5a5850; line-height: 1.5; }}

        /* Audit trail */
        .audit-row {{ display: flex; gap: 12px; padding: 6px 0; border-bottom: 1px solid #f0efe9; font-family: 'DM Mono', monospace; font-size: 0.65rem; }}
        .audit-row:last-child {{ border: none; }}
        .audit-stage {{ color: #1a1a18; font-weight: 500; width: 160px; flex-shrink: 0; }}
        .audit-status-ok  {{ color: #0a7c52; width: 60px; flex-shrink: 0; }}
        .audit-status-err {{ color: #c41c3a; width: 60px; flex-shrink: 0; }}
        .audit-ts {{ color: #9a9888; width: 80px; flex-shrink: 0; }}
        .audit-dur {{ color: #5a5850; }}

        /* Signature */
        .signature-box {{ background: #f8f7f3; border: 1px solid #e2e0d8; border-radius: 10px; padding: 16px 20px; display: grid; grid-template-columns: 1fr 1fr; gap: 8px; }}
        .sig-field {{ font-size: 0.72rem; }}
        .sig-label {{ color: #9a9888; font-family: 'DM Mono', monospace; font-size: 0.6rem; text-transform: uppercase; letter-spacing: 0.08em; }}
        .sig-value {{ color: #1a1a18; font-family: 'DM Mono', monospace; margin-top: 2px; }}

        /* Print button */
        .print-btn {{ position: fixed; bottom: 24px; right: 24px; background: linear-gradient(135deg, #1d4ed8, #6d28d9); color: #fff; border: none; border-radius: 8px; padding: 10px 20px; font-family: 'DM Sans', sans-serif; font-size: 0.85rem; font-weight: 600; cursor: pointer; box-shadow: 0 4px 12px rgba(29,78,216,0.3); }}
        .print-btn:hover {{ opacity: 0.9; }}
        """

        # Build section HTML helpers
        def sec(title: str, inner: str, extra_style: str = "") -> str:
            return f"""
            <div class="section" style="{extra_style}">
                <div class="section-title">{title}</div>
                {inner}
            </div>"""

        # Executive summary narrative
        exec_html = f"""
        <p style="font-size:0.85rem;color:#5a5850;line-height:1.65;margin-bottom:10px">{self.executive_summary.content}</p>
        {''.join(f'<p style="font-size:0.8rem;color:#5a5850;margin-bottom:6px">• {item.get("value","")}</p>' for item in self.executive_summary.items) if self.executive_summary.items else ''}
        """

        # Patient metadata
        meta_html = '<div style="display:grid;grid-template-columns:1fr 1fr;gap:6px 24px;">'
        for item in self.patient_metadata.items:
            meta_html += f'<div class="meta-row"><span class="meta-label">{item.get("label","")}:</span><span class="meta-value">{item.get("value","—")}</span></div>'
        meta_html += '</div>'

        # Clinical findings
        findings_html = ""
        for item in self.clinical_findings.items:
            label = item.get("label","")
            values = item.get("values", [])
            if values:
                findings_html += f'<div style="margin-bottom:10px"><div style="font-family:DM Mono,monospace;font-size:0.62rem;color:#9a9888;text-transform:uppercase;letter-spacing:0.1em;margin-bottom:4px">{label}</div>'
                findings_html += ''.join(f'<span style="display:inline-block;background:#eff6ff;color:#1d4ed8;border:1px solid #bfdbfe;border-radius:4px;padding:2px 8px;font-family:DM Mono,monospace;font-size:0.68rem;margin:2px">{v}</span>' for v in values)
                findings_html += '</div>'

        # Code analysis
        icd_chips = ""
        cpt_chips = ""
        for item in self.code_analysis.items:
            system = item.get("system","")
            code   = item.get("code","")
            desc   = item.get("description","")
            conf   = item.get("confidence","")
            cls    = "cpt" if system == "CPT" else ""
            if system == "ICD-10-CM":
                icd_chips += f'<div class="code-chip"><div class="code-number">{code}</div><div class="code-desc">{desc}</div><div class="code-conf">{conf} confidence</div></div>'
            else:
                cpt_chips += f'<div class="code-chip"><div class="code-number cpt">{code}</div><div class="code-desc">{desc}</div><div class="code-conf">{conf} confidence</div></div>'

        codes_html = ""
        if icd_chips:
            codes_html += f'<div style="font-family:DM Mono,monospace;font-size:0.6rem;color:#9a9888;text-transform:uppercase;letter-spacing:0.1em;margin-bottom:6px">ICD-10-CM Diagnoses</div><div class="codes-grid">{icd_chips}</div>'
        if cpt_chips:
            codes_html += f'<div style="font-family:DM Mono,monospace;font-size:0.6rem;color:#9a9888;text-transform:uppercase;letter-spacing:0.1em;margin:12px 0 6px">CPT Procedures</div><div class="codes-grid">{cpt_chips}</div>'
        if not codes_html:
            codes_html = '<p style="color:#9a9888;font-size:0.75rem">No codes mapped</p>'

        # Rule evaluation
        rules_html = ""
        for item in self.rule_evaluation.items:
            status = item.get("status","")
            icon   = "✓" if status=="pass" else ("✗" if status=="fail" else "!")
            cls    = "ri-pass" if status=="pass" else ("ri-fail" if status=="fail" else "ri-warn")
            rules_html += f"""
            <div class="rule-row">
                <div class="rule-icon {cls}">{icon}</div>
                <div>
                    <div class="rule-id">{item.get("rule_id","")}</div>
                    <div class="rule-reason">{item.get("reason","")}</div>
                </div>
            </div>"""
        if not rules_html:
            rules_html = '<p style="color:#9a9888;font-size:0.75rem">No rules evaluated</p>'

        # Edge cases
        edges_html = ""
        for item in self.edge_case_analysis.items:
            sev      = item.get("severity","").lower()
            cls      = "warn" if sev in ("medium","low") else ""
            mismatch = ""
            if item.get("image_signal"):
                mismatch = f'<div style="font-size:0.68rem;color:#92400e;margin-top:4px">Imaging: {item["image_signal"]} | Clinical text: {item.get("text_signal","")} | Score: {item.get("mismatch_score","")}</div>'
            edges_html += f"""
            <div class="edge-card {cls}">
                <div class="edge-type">{item.get("type","")} · {item.get("severity","")}</div>
                <div class="edge-desc">{item.get("description","")}</div>
                {mismatch}
                <div class="edge-rec">→ {item.get("recommendation","")}</div>
            </div>"""
        if not edges_html:
            edges_html = '<p style="color:#0a7c52;font-size:0.78rem;background:#ecfdf5;border:1px solid #a7f3d0;border-radius:6px;padding:8px 12px">✓ No edge cases detected — all clinical anomaly checks passed</p>'

        # Guidelines
        citations_html = ""
        for item in self.guideline_citations.items:
            citations_html += f"""
            <div class="citation">
                <div class="citation-source">{item.get("source","")}</div>
                <div class="citation-text">{item.get("excerpt","")}</div>
            </div>"""
        if not citations_html:
            citations_html = '<p style="color:#9a9888;font-size:0.75rem">No guideline passages retrieved</p>'

        # Imaging
        img_content = self.imaging_analysis.content
        imaging_html = f'<p style="font-size:0.8rem;color:#5a5850">{img_content}</p>' if img_content else '<p style="color:#9a9888;font-size:0.75rem">No imaging analysis performed</p>'

        # Risk assessment
        risk_html = f'<p style="font-size:0.82rem;color:#5a5850;line-height:1.65;margin-bottom:10px">{self.risk_assessment.content}</p>'
        if self.risk_assessment.items:
            for item in self.risk_assessment.items:
                sev = item.get("severity","").lower()
                col = "#c41c3a" if "high" in sev or "critical" in sev else ("#92400e" if "medium" in sev else "#0a7c52")
                bg  = "#fff1f2" if "high" in sev or "critical" in sev else ("#fffbeb" if "medium" in sev else "#ecfdf5")
                risk_html += f'<div style="background:{bg};border-left:3px solid {col};padding:8px 12px;border-radius:0 6px 6px 0;margin-bottom:6px;font-size:0.75rem;color:{col}">{item.get("text","")}</div>'

        # Actions
        actions_html = '<div class="action-list">'
        for i, item in enumerate(self.recommended_actions.items, 1):
            priority = item.get("priority","neutral")
            cls_map  = {"critical":"danger","high":"danger","medium":"warn","low":"neutral","info":"primary"}
            cls      = cls_map.get(priority, "neutral")
            col_map  = {"danger":"#c41c3a","warn":"#92400e","primary":"#1d4ed8","neutral":"#5a5850"}
            col      = col_map.get(cls,"#5a5850")
            bg_map   = {"danger":"#fff1f2","warn":"#fffbeb","primary":"#eff6ff","neutral":"#f8f7f3"}
            bg       = bg_map.get(cls,"#f8f7f3")
            actions_html += f"""
            <div class="action-item {cls}">
                <div class="action-num" style="background:{bg};color:{col};border:1.5px solid {col}">{i}</div>
                <div class="action-text">{item.get("text","")}</div>
            </div>"""
        actions_html += '</div>'

        # Audit trail
        audit_html = ""
        for item in self.audit_trail.items:
            status = item.get("status","")
            cls    = "audit-status-ok" if status=="SUCCESS" else "audit-status-err"
            ts     = item.get("timestamp","")[-15:-7] if len(item.get("timestamp",""))>15 else item.get("timestamp","")
            audit_html += f"""
            <div class="audit-row">
                <div class="audit-stage">{item.get("stage","")}</div>
                <div class="{cls}">{status}</div>
                <div class="audit-ts">{ts}</div>
                <div class="audit-dur">{item.get("duration_ms","")}ms</div>
            </div>"""
        if not audit_html:
            audit_html = '<p style="color:#9a9888;font-size:0.75rem">No audit entries</p>'

        # Signature
        sig_items = self.report_signature.items
        sig_html = '<div class="signature-box">'
        for item in sig_items:
            sig_html += f'<div class="sig-field"><div class="sig-label">{item.get("label","")}</div><div class="sig-value">{item.get("value","")}</div></div>'
        sig_html += '</div>'

        # Reasoning chain
        chain_html = ""
        for item in self.audit_trail.items[:0]:  # handled separately below
            pass
        reasoning_chain = getattr(self, '_reasoning_chain', [])
        for step in reasoning_chain:
            chain_html += f"""
            <div class="chain-step">
                <div class="chain-dot"></div>
                <div>
                    <div class="chain-stage">{step.get("stage","")} · {step.get("confidence","")}</div>
                    <div class="chain-outcome">{step.get("outcome","")}</div>
                </div>
            </div>"""

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>ClaimIQ Report — {self.claim_id}</title>
<style>{css}</style>
</head>
<body>
<div class="page">

  <!-- Header -->
  <div class="report-header">
    <div class="logo-row">
      <div class="logo-mark">Rx</div>
      <div>
        <div class="logo-name">ClaimIQ</div>
        <div class="logo-sub">Healthcare Claims Adjudication Agent — Automated Report</div>
      </div>
    </div>
    <div class="meta-grid">
      <div class="meta-row"><span class="meta-label">Report ID</span><span class="meta-value">{self.report_id}</span></div>
      <div class="meta-row"><span class="meta-label">Generated</span><span class="meta-value">{self.generated_at.strftime('%Y-%m-%d %H:%M:%S UTC')}</span></div>
      <div class="meta-row"><span class="meta-label">Claim ID</span><span class="meta-value">{self.claim_id}</span></div>
      <div class="meta-row"><span class="meta-label">Audit Trace</span><span class="meta-value">{self.audit_trace_id}</span></div>
      <div class="meta-row"><span class="meta-label">Decided</span><span class="meta-value">{self.decided_at.strftime('%Y-%m-%d %H:%M:%S UTC')}</span></div>
      <div class="meta-row"><span class="meta-label">Version</span><span class="meta-value">{self.report_version}</span></div>
    </div>
  </div>

  <!-- Decision Banner -->
  <div class="decision-banner">
    <div class="decision-icon">{dec_icon}</div>
    <div>
      <div class="decision-title">{dec_label}</div>
      <div class="decision-conf">{conf_pct} confidence · {self.claim_id}</div>
      <div class="decision-narrative">{self.executive_summary.content}</div>
    </div>
  </div>

  {sec("Patient & Claim Information", meta_html)}
  {sec("Clinical Findings", findings_html)}
  {sec("Medical Code Analysis", codes_html)}
  {sec("Policy Rule Evaluation", rules_html)}
  {sec("Edge Case Analysis", edges_html)}
  {sec("Clinical Guideline Citations", citations_html)}
  {sec("Imaging Analysis", imaging_html)}
  {sec("Risk Assessment", risk_html)}
  {sec("Recommended Actions", actions_html)}
  {sec("Pipeline Audit Trail", audit_html)}
  {sec("Report Signature & Certification", sig_html)}

</div>

<button class="print-btn no-print" onclick="window.print()">🖨 Print / Save PDF</button>

</body>
</html>"""

    def to_pdf(self, output_path: Optional[str] = None) -> Optional[bytes]:
        """
        Converts HTML report to PDF using WeasyPrint.
        Requires: pip install weasyprint
        Returns PDF bytes, or saves to output_path if provided.
        """
        try:
            from weasyprint import HTML
            html_content = self.to_html()
            pdf = HTML(string=html_content).write_pdf()
            if output_path:
                with open(output_path, "wb") as f:
                    f.write(pdf)
                logger.info(f"PDF saved to {output_path}")
            return pdf
        except ImportError:
            logger.error("WeasyPrint not installed. Run: pip install weasyprint")
            return None
        except Exception as e:
            logger.error(f"PDF generation failed: {e}")
            return None

    def _section_dict(self, s: ReportSection) -> dict:
        return {"title": s.title, "content": s.content, "items": s.items}


# ─────────────────────────────────────────────
# REPORT GENERATOR
# ─────────────────────────────────────────────

class ReportGenerator:
    """
    Generates a complete structured ClinicalReport from an AdjudicationResult.

    Usage:
        gen    = ReportGenerator()
        report = gen.generate(result, claim)
        html   = report.to_html()
        text   = report.to_text()
        data   = report.to_dict()
    """

    def generate(
        self,
        result: AdjudicationResult,
        claim:  Optional[TokenizedClaimInput] = None,
        audit_entries: Optional[list] = None,
    ) -> ClinicalReport:
        """
        Generates a full ClinicalReport from an adjudication result.

        Args:
            result:        AdjudicationResult from the pipeline
            claim:         TokenizedClaimInput (for patient metadata)
            audit_entries: list of AuditEntry from get_audit_logger().get_trace()
        """
        now     = datetime.utcnow()
        report_id = f"RPT-{result.claim_id}-{now.strftime('%Y%m%d%H%M%S')}"

        dec        = result.decision.value
        conf       = result.confidence_score
        conf_pct   = f"{conf:.0%}"
        blocking   = [ev for ev in result.rule_evaluations if not ev.passed and ev.action.value == "reject"]
        warnings   = [ev for ev in result.rule_evaluations if not ev.passed and ev.action.value == "flag_review"]
        edge_cases = result.edge_cases or []
        has_mismatch = any(ec.edge_case_type.value == "image_text_mismatch" for ec in edge_cases)

        report = ClinicalReport(
            report_id       = report_id,
            generated_at    = now,
            report_version  = REPORT_VERSION,
            claim_id        = result.claim_id,
            audit_trace_id  = result.audit_trace_id,
            decided_at      = result.decided_at,
            decision        = dec,
            confidence_score= conf,
            decision_colour = "#0a7c52" if dec=="approved" else ("#c41c3a" if dec=="rejected" else "#92400e"),
            executive_summary   = self._build_executive_summary(result, blocking, warnings, edge_cases, conf_pct, claim),
            patient_metadata    = self._build_patient_metadata(result, claim),
            clinical_findings   = self._build_clinical_findings(result),
            code_analysis       = self._build_code_analysis(result),
            rule_evaluation     = self._build_rule_evaluation(result),
            edge_case_analysis  = self._build_edge_case_analysis(result),
            guideline_citations = self._build_guideline_citations(result),
            imaging_analysis    = self._build_imaging_analysis(result),
            risk_assessment     = self._build_risk_assessment(result, blocking, edge_cases, has_mismatch),
            recommended_actions = self._build_recommended_actions(result, blocking, warnings, edge_cases, has_mismatch, claim),
            audit_trail         = self._build_audit_trail(result, audit_entries),
            report_signature    = self._build_signature(result, report_id, now),
        )

        # Attach reasoning chain for HTML rendering
        if result.explainability and result.explainability.reasoning_chain:
            report._reasoning_chain = [
                {
                    "stage":      step.stage.value.replace("_"," ").title(),
                    "confidence": f"{step.confidence:.0%}",
                    "outcome":    step.outcome,
                }
                for step in result.explainability.reasoning_chain
            ]
        else:
            report._reasoning_chain = []

        return report

    # ── Section builders ─────────────────────────────────────────────────────

    def _build_executive_summary(self, result, blocking, warnings, edge_cases, conf_pct, claim) -> ReportSection:
        dec  = result.decision.value
        plan = claim.patient_info.insurance_plan.value if claim else "unknown"
        n_rules = len(result.rule_evaluations)

        if dec == "approved":
            narrative = (
                f"This claim has been approved with {conf_pct} confidence. "
                f"All {n_rules} applicable policy rule(s) passed and no clinical anomalies were detected. "
                f"The submitted diagnosis and procedure codes are medically consistent and are covered under the patient's {plan} insurance plan. "
                f"No further action is required — this claim may proceed to payment processing."
            )
            items = [{"value": "All policy rules passed with no blocking failures."},
                     {"value": f"Coded {len(result.icd10_codes)} ICD-10 diagnosis(es) and {len(result.cpt_codes)} CPT procedure(s)."},
                     {"value": f"No edge cases or clinical anomalies detected."}]

        elif dec == "rejected":
            primary = blocking[0] if blocking else None
            rule_detail = f"Rule {primary.rule_id}: {primary.reason}" if primary else "Policy rule failure"
            narrative = (
                f"This claim has been rejected with {conf_pct} confidence. "
                f"The primary rejection reason is: {rule_detail}. "
                f"The claim cannot be approved in its current form and requires correction before resubmission. "
                f"Please review the Required Actions section below for specific steps to resolve this rejection."
            )
            items = [{"value": f"Blocking failures: {len(blocking)} rule(s) triggered a REJECT action."}]
            if warnings:
                items.append({"value": f"Additional warnings: {len(warnings)} rule(s) flagged for review."})

        else:  # needs_review
            reasons = []
            if warnings:   reasons.append(f"{len(warnings)} policy rule(s) require payer verification")
            if edge_cases: reasons.append(f"{len(edge_cases)} clinical anomaly(ies) detected")
            reason_str = "; ".join(reasons) if reasons else "policy concerns requiring manual evaluation"
            narrative = (
                f"This claim has been flagged for manual review with {conf_pct} confidence. "
                f"Issues identified: {reason_str}. "
                f"A qualified clinical reviewer must evaluate this claim before a final adjudication decision can be made. "
                f"Do not process for payment until review is complete."
            )
            items = [{"value": r} for r in result.reasons[:5]]

        return ReportSection(title="Executive Summary", content=narrative, items=items)

    def _build_patient_metadata(self, result, claim) -> ReportSection:
        items = [
            {"label": "Claim ID",       "value": result.claim_id},
            {"label": "Audit Trace",    "value": result.audit_trace_id},
            {"label": "Decided At",     "value": result.decided_at.strftime("%Y-%m-%d %H:%M UTC")},
            {"label": "Pipeline Ver.",  "value": result.pipeline_version},
        ]
        if claim:
            pi = claim.patient_info
            items += [
                {"label": "Patient ID",    "value": pi.token_patient_id},
                {"label": "Age Band",      "value": pi.age_band},
                {"label": "Sex",           "value": pi.sex},
                {"label": "Plan",          "value": pi.insurance_plan.value.upper()},
                {"label": "Policy Token",  "value": pi.token_policy},
            ]
        return ReportSection(title="Patient & Claim Information", content="", items=items)

    def _build_clinical_findings(self, result) -> ReportSection:
        items = []
        # We get entities from the coding result since extraction result not on AdjudicationResult
        if result.icd10_codes:
            items.append({"label": "Diagnosed Conditions", "values": [f"{c.code}: {c.description}" for c in result.icd10_codes]})
        if result.cpt_codes:
            items.append({"label": "Procedures Identified", "values": [f"{c.code}: {c.description}" for c in result.cpt_codes]})
        if result.edge_cases:
            items.append({"label": "Clinical Anomalies", "values": [ec.edge_case_type.value.replace("_"," ").title() for ec in result.edge_cases]})

        content = result.explainability.summary if result.explainability else ""
        return ReportSection(title="Clinical Findings", content=content, items=items)

    def _build_code_analysis(self, result) -> ReportSection:
        items = []
        for c in result.icd10_codes:
            items.append({
                "system":      "ICD-10-CM",
                "code":        c.code,
                "description": c.description,
                "confidence":  f"{c.confidence:.0%}",
                "exact":       "exact match" if c.is_exact_match else "fuzzy match",
            })
        for c in result.cpt_codes:
            items.append({
                "system":      "CPT",
                "code":        c.code,
                "description": c.description,
                "confidence":  f"{c.confidence:.0%}",
                "exact":       "exact match" if c.is_exact_match else "fuzzy match",
            })
        content = f"{len(result.icd10_codes)} ICD-10-CM diagnosis code(s) and {len(result.cpt_codes)} CPT procedure code(s) mapped."
        return ReportSection(title="Medical Code Analysis", content=content, items=items)

    def _build_rule_evaluation(self, result) -> ReportSection:
        items = []
        for ev in result.rule_evaluations:
            if ev.passed:
                status = "pass"
            elif ev.action.value == "reject":
                status = "fail"
            else:
                status = "warn"
            items.append({
                "rule_id": ev.rule_id,
                "status":  status,
                "action":  ev.action.value,
                "reason":  ev.reason,
                "label":   ev.rule_name if hasattr(ev, "rule_name") else ev.rule_id,
                "value":   ev.reason,
            })
        n_pass = sum(1 for ev in result.rule_evaluations if ev.passed)
        n_fail = len(result.rule_evaluations) - n_pass
        content = f"{len(result.rule_evaluations)} rules evaluated — {n_pass} passed, {n_fail} failed."
        return ReportSection(title="Policy Rule Evaluation", content=content, items=items)

    def _build_edge_case_analysis(self, result) -> ReportSection:
        items = []
        for ec in result.edge_cases:
            items.append({
                "type":         ec.edge_case_type.value,
                "severity":     ec.severity.value,
                "description":  ec.description,
                "recommendation": ec.recommendation if hasattr(ec,"recommendation") else "",
                "image_signal": ec.image_signal if hasattr(ec,"image_signal") else None,
                "text_signal":  ec.text_signal  if hasattr(ec,"text_signal")  else None,
                "mismatch_score": f"{ec.mismatch_score:.2f}" if hasattr(ec,"mismatch_score") and ec.mismatch_score else None,
            })
        content = f"{len(result.edge_cases)} edge case(s) detected." if result.edge_cases else "No edge cases detected."
        return ReportSection(title="Edge Case Analysis", content=content, items=items)

    def _build_guideline_citations(self, result) -> ReportSection:
        items = []
        passages = result.rag_passages or []
        for p in passages[:5]:
            items.append({
                "source":  p.source,
                "passage_id": p.passage_id if hasattr(p,"passage_id") else "",
                "relevance": f"{p.relevance:.2f}",
                "excerpt": p.content[:250] + "..." if len(p.content) > 250 else p.content,
            })
        content = f"{len(passages)} clinical guideline passage(s) retrieved and evaluated."
        return ReportSection(title="Clinical Guideline Citations", content=content, items=items)

    def _build_imaging_analysis(self, result) -> ReportSection:
        img = result.imaging_result
        if not img:
            return ReportSection(title="Imaging Analysis", content="No imaging analysis was performed for this claim. Imaging mode was set to SKIPPED.", items=[])

        content = (
            f"Imaging analysis was performed using the {img.mode_used.value} model. "
            f"Classification result: '{img.class_label}' with {img.confidence:.0%} confidence."
        )
        if img.icd10_suggestion:
            content += f" Suggested ICD-10 code: {img.icd10_suggestion}."

        items = [
            {"label": "Mode",        "value": img.mode_used.value},
            {"label": "Class Label", "value": img.class_label or "—"},
            {"label": "Confidence",  "value": f"{img.confidence:.0%}"},
            {"label": "ICD-10 Hint", "value": img.icd10_suggestion or "—"},
        ]
        return ReportSection(title="Imaging Analysis", content=content, items=items)

    def _build_risk_assessment(self, result, blocking, edge_cases, has_mismatch) -> ReportSection:
        dec  = result.decision.value
        risk_items = []

        if dec == "approved":
            content = "Risk level: LOW. This claim passed all automated checks and is cleared for payment processing. Standard post-payment audit procedures apply."
        elif dec == "rejected":
            content = f"Risk level: HIGH. This claim contains {len(blocking)} blocking policy violation(s) that prevent approval. Resubmission will be required after the issues identified below are resolved."
            for ev in blocking:
                risk_items.append({"severity": "high", "text": f"BLOCKING — {ev.rule_id}: {ev.reason}"})
        else:
            content = "Risk level: MEDIUM. This claim requires human review before a payment decision can be made. The following issues were identified:"
            for ev in result.rule_evaluations:
                if not ev.passed:
                    risk_items.append({"severity": "medium", "text": f"Rule {ev.rule_id}: {ev.reason}"})

        for ec in edge_cases:
            sev = ec.severity.value.lower()
            risk_items.append({"severity": sev, "text": f"{ec.edge_case_type.value}: {ec.description}"})

        if has_mismatch:
            risk_items.append({"severity": "high", "text": "IMAGE_TEXT_MISMATCH: Imaging and clinical text diagnoses disagree — specialist review required before any payment decision."})

        return ReportSection(title="Risk Assessment", content=content, items=risk_items)

    def _build_recommended_actions(self, result, blocking, warnings, edge_cases, has_mismatch, claim) -> ReportSection:
        dec     = result.decision.value
        plan    = claim.patient_info.insurance_plan.value if claim else "unknown"
        items   = []
        n       = 1

        if dec == "approved":
            items.append({"priority":"info",     "text": f"Proceed to payment processing — all {len(result.rule_evaluations)} policy checks passed and no anomalies detected."})
            items.append({"priority":"info",     "text": f"File audit record <strong>{result.audit_trace_id}</strong> with the claim documentation for compliance purposes."})
            items.append({"priority":"low",      "text": "No further clinical review required. Standard post-payment audit procedures apply."})
            if result.rag_passages:
                items.append({"priority":"low",  "text": f"Clinical necessity supported by {len(result.rag_passages)} guideline passage(s) — see Citations section."})

        elif dec == "rejected":
            for ev in blocking:
                rule_id = ev.rule_id
                reason  = ev.reason
                if rule_id.startswith("COMPAT"):
                    items.append({"priority":"critical", "text": f"<strong>{rule_id}</strong>: Obtain and attach supporting clinical documentation establishing the required diagnosis-procedure relationship. {reason}"})
                elif rule_id.startswith("COV"):
                    items.append({"priority":"critical", "text": f"<strong>{rule_id}</strong>: Coverage exclusion under {plan.upper()} plan. Options: (a) upgrade patient to STANDARD or PREMIUM plan, (b) seek a coverage exception with medical necessity documentation, (c) bill the patient directly if applicable. {reason}"})
                elif rule_id.startswith("AGE"):
                    items.append({"priority":"critical", "text": f"<strong>{rule_id}</strong>: Age restriction applies. If a clinical exception exists, obtain specialist documentation and written justification. {reason}"})
                else:
                    items.append({"priority":"critical", "text": f"<strong>{rule_id}</strong>: {reason}"})
            items.append({"priority":"high",  "text": "Correct ALL identified issues before resubmission. Partial corrections will result in re-rejection."})
            items.append({"priority":"medium","text": f"Reference audit trace <strong>{result.audit_trace_id}</strong> in all correspondence and resubmission documentation."})
            items.append({"priority":"low",   "text": "If you believe this rejection is in error, initiate the payer appeals process with supporting clinical evidence."})

        else:  # needs_review
            for ev in warnings:
                if ev.rule_id.startswith("AUTH"):
                    items.append({"priority":"high",   "text": f"<strong>{ev.rule_id}</strong>: Submit prior authorization request to the payer BEFORE claim payment. Include: diagnosis codes, clinical indication, treating physician details, and prior treatment history. {ev.reason}"})
                else:
                    items.append({"priority":"medium", "text": f"<strong>{ev.rule_id}</strong>: {ev.reason}"})

            for ec in edge_cases:
                sev  = ec.severity.value.lower()
                pri  = "critical" if sev in ("critical","high") else "medium"
                if ec.edge_case_type.value == "image_text_mismatch":
                    items.append({"priority":"critical", "text": f"<strong>IMAGING MISMATCH</strong>: Imaging suggests '{ec.image_signal}' but clinical text suggests '{ec.text_signal}' (mismatch score: {ec.mismatch_score:.2f}). Radiologist review and treating physician attestation required before adjudication."})
                elif ec.edge_case_type.value == "missing_diagnosis":
                    items.append({"priority":"critical", "text": f"<strong>MISSING DIAGNOSIS</strong>: {ec.description} Submit ICD-10 diagnosis codes supporting medical necessity for all claimed procedures."})
                elif ec.edge_case_type.value == "low_confidence_extraction":
                    items.append({"priority":"medium",  "text": f"<strong>LOW CONFIDENCE</strong>: {ec.description} Clinical reviewer should verify extracted codes against source documentation."})
                else:
                    items.append({"priority":pri, "text": f"<strong>{ec.edge_case_type.value}</strong>: {ec.description} {ec.recommendation if hasattr(ec,'recommendation') else ''}"})

            items.append({"priority":"high",   "text": "Route to clinical reviewer queue immediately. Do NOT process for payment until review is complete and approved."})
            items.append({"priority":"medium", "text": f"Target review turnaround: 48 business hours. Reference audit trace <strong>{result.audit_trace_id}</strong>."})

        return ReportSection(title="Recommended Actions", content="", items=items)

    def _build_audit_trail(self, result, audit_entries) -> ReportSection:
        items = []
        if audit_entries:
            for entry in audit_entries:
                items.append({
                    "stage":       entry.stage.value if hasattr(entry.stage,"value") else str(entry.stage),
                    "status":      entry.status.value if hasattr(entry.status,"value") else str(entry.status),
                    "timestamp":   entry.timestamp.isoformat() if hasattr(entry,"timestamp") else "",
                    "duration_ms": entry.duration_ms if hasattr(entry,"duration_ms") else 0,
                    "error":       entry.error_message or "",
                })
        elif result.explainability and result.explainability.reasoning_chain:
            for step in result.explainability.reasoning_chain:
                items.append({
                    "stage":       step.stage.value.replace("_"," ").title(),
                    "status":      "SUCCESS",
                    "timestamp":   result.decided_at.isoformat(),
                    "duration_ms": "—",
                    "error":       "",
                })
        content = f"{len(items)} pipeline stage(s) recorded. No PHI present in audit trail."
        return ReportSection(title="Pipeline Audit Trail", content=content, items=items)

    def _build_signature(self, result, report_id, now) -> ReportSection:
        items = [
            {"label": "Report ID",       "value": report_id},
            {"label": "Generated By",    "value": "ClaimIQ Adjudication Agent v1.0"},
            {"label": "Generated At",    "value": now.strftime("%Y-%m-%d %H:%M:%S UTC")},
            {"label": "Pipeline Ver.",   "value": result.pipeline_version},
            {"label": "Claim ID",        "value": result.claim_id},
            {"label": "Audit Trace",     "value": result.audit_trace_id},
            {"label": "Decision",        "value": result.decision.value.upper().replace("_"," ")},
            {"label": "Confidence",      "value": f"{result.confidence_score:.4f}"},
            {"label": "PHI Status",      "value": "TOKENIZED — No PHI in this report"},
            {"label": "Report Format",   "value": f"ClaimIQ Report v{REPORT_VERSION}"},
        ]
        content = "This report was generated automatically by the ClaimIQ Healthcare Claims Adjudication Agent. All patient identifiers have been replaced with cryptographic vault tokens — no Protected Health Information (PHI) is present in this document. This report is for adjudication purposes only and does not constitute medical advice."
        return ReportSection(title="Report Signature & Certification", content=content, items=items)
